-- Owner-scoped Stars revenue for bot accounts. A bot wallet is deliberately a
-- separate bucket from the bot user identity's personal Stars balance: an
-- operator sees incoming XTR invoice proceeds as the bot's current balance in
-- payments.getStarsRevenueStats, while the bot spends from its own ledger when
-- it buys something (for example giftPremiumSubscription) in the future.
--
-- These are internal telesrv ledgers only; no blockchain, wallet, TON node or
-- Fragment endpoint is contacted. Balance rows are never seeded with a starting
-- grant: a bot earns stars only through an actual paid invoice.

CREATE TABLE public.bot_stars_balances (
    bot_user_id bigint PRIMARY KEY,
    balance bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT bot_stars_balances_shape_check CHECK (bot_user_id>0 AND balance>=0)
);

CREATE TABLE public.bot_stars_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_user_id bigint NOT NULL,
    actor_user_id bigint NOT NULL,
    amount bigint NOT NULL,
    reason text NOT NULL,
    peer_type text DEFAULT '' NOT NULL,
    peer_id bigint DEFAULT 0 NOT NULL,
    invoice_key text,
    date integer NOT NULL,
    CONSTRAINT bot_stars_transactions_shape_check CHECK (
        bot_user_id>0 AND actor_user_id>0 AND amount<>0 AND date>0 AND
        ((peer_type='' AND peer_id=0) OR (peer_type IN ('user','channel') AND peer_id>0)))
);
CREATE INDEX bot_stars_transactions_bot_idx
    ON public.bot_stars_transactions(bot_user_id,id DESC);

-- One row per settled invoice keeps the credit idempotent across retried
-- payments.sendPaymentForm calls: the replay hits the unique key instead of
-- minting a second credit. `amount` is the absolute moved amount; the sign
-- lives in the matching bot_stars_transactions row, so a refund receipt is
-- stored as a positive magnitude too.
CREATE TABLE public.bot_stars_payments (
    invoice_key text PRIMARY KEY,
    bot_user_id bigint NOT NULL,
    payer_user_id bigint NOT NULL,
    amount bigint NOT NULL,
    balance_after bigint NOT NULL,
    settled_at integer NOT NULL,
    CONSTRAINT bot_stars_payments_shape_check CHECK (
        bot_user_id>0 AND payer_user_id>0 AND amount>0 AND
        balance_after>=0 AND settled_at>0)
);
