-- XTR invoices sent by a bot as a chat message.
--
-- payments.sendPaymentForm carries no purpose in this layer, so the client only
-- sends the message id and the server resolves the price from this record. The
-- row is therefore the settlement authority: a replayed sendPaymentForm must
-- find the same charge id rather than charge twice.
--
-- charge_id is unique because refundStarPayment resolves an invoice only by
-- telegram_payment_charge_id.

CREATE TABLE public.bot_invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_user_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    message_id integer NOT NULL,
    title character varying(32) DEFAULT ''::character varying NOT NULL,
    description character varying(255) DEFAULT ''::character varying NOT NULL,
    amount bigint NOT NULL,
    currency character varying(8) DEFAULT 'XTR'::character varying NOT NULL,
    payload character varying(64) DEFAULT ''::character varying NOT NULL,
    charge_id character varying(64) DEFAULT ''::character varying NOT NULL,
    payer_user_id bigint NOT NULL DEFAULT 0,
    paid boolean DEFAULT false NOT NULL,
    refunded boolean DEFAULT false NOT NULL,
    paid_at integer DEFAULT 0 NOT NULL,
    date integer NOT NULL,
    CONSTRAINT bot_invoices_shape_check CHECK (
        bot_user_id>0 AND chat_id<>0 AND message_id>0 AND amount>0 AND date>0 AND
        currency='XTR' AND
        (paid = false OR (charge_id<>'' AND payer_user_id>0 AND paid_at>0)) AND
        (refunded = false OR paid))
);

-- The payment form path looks the invoice up by its own message.
CREATE UNIQUE INDEX bot_invoices_message_idx
    ON public.bot_invoices(bot_user_id,chat_id,message_id);

-- Only paid invoices carry a charge id, so a plain index would collide on the
-- empty default.
CREATE UNIQUE INDEX bot_invoices_charge_idx
    ON public.bot_invoices(charge_id) WHERE charge_id<>'';

CREATE INDEX bot_invoices_bot_date_idx
    ON public.bot_invoices(bot_user_id,date DESC);
