server {
    listen 80;
    listen [::]:80;
    server_name www.safelink.chat;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://www.safelink.chat$request_uri;
    }
}
